FROM kasmweb/core-kali-rolling:1.12.0-rolling
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install

# TTI Install packages
RUN apt update
RUN apt install -y zaproxy vim-gtk3

# TTI Copy custom yaml
COPY ./kasmvnc.yaml /etc/kasmvnc/kasmvnc.yaml
WORKDIR $HOME

######### Customize Container Here ###########



######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000