---
- name: Setup Swarm Workers
  vars_prompt:
    - name: manager_ip
      prompt: "Manager IP"
      private: false
    - name: swarm_token
      prompt: "Swarm Token"
      private: false
  hosts: workers
  become: true
  become_user: root
  roles:
    - docker
  tasks:
    - name: Confirm Pip
      ansible.builtin.apt:
        name: python3-pip
        update_cache: true
    - name: Install Docker Module
      ansible.builtin.pip:
        name: docker
    - name: Join Swarm
      community.docker.docker_swarm:
        state: join
        join_token: "{{ swarm_token }}"
        remote_addrs: ["{{ manager_ip }}:2377"]
    - name: Pull Terminal Image
      community.docker.docker_image:
        source: pull
        name: taggarttech/tti-kasm-terminal
    - name: Pull Kali Image
      community.docker.docker_image:
        source: pull
        name: taggarttech/tti-kasm-kali
